// Preview-only snapshots: choosing a direction never changes the application theme.
export type PaletteTokens = Record<`--${string}`, string>
export type PaletteMode = 'light' | 'dark'
export type WorkshopPalette = {
  id: string
  name: string
  description: string
  light: PaletteTokens
  dark: PaletteTokens
}
const current = {
  light: {
    '--card': '#fcfdfc',
    '--card-foreground': '#26342d',
    '--popover': '#fcfdfc',
    '--popover-foreground': '#26342d',
    '--selection': '#46564d',
    '--selection-foreground': '#f8fbf9',
    '--selection-surface': '#e0e8e3',
    '--primary': '#24634b',
    '--primary-foreground': '#fcfdfc',
    '--secondary': '#e8edea',
    '--secondary-foreground': '#26342d',
    '--muted': '#eff2f0',
    '--muted-foreground': '#5b6961',
    '--accent': '#e2ece6',
    '--accent-foreground': '#26342d',
    '--destructive': '#962f43',
    '--destructive-foreground': '#fff8f9',
    '--border': '#c5cec9',
    '--input': '#7d8b83',
    '--ring': '#24634b',
    '--chart-1': '#24634b',
    '--chart-2': '#557865',
    '--chart-3': '#a46f2c',
    '--chart-4': '#7b4f2f',
    '--chart-5': '#962f43',
    '--status-info': '#365f4d',
    '--status-info-surface': '#e0ede5',
    '--status-warning': '#87571f',
    '--status-warning-surface': '#f1e2c8',
    '--radius': '0.5rem',
    '--control-height': '2.5rem',
    '--sidebar': '#f0f3f1',
    '--sidebar-foreground': '#26342d',
    '--sidebar-primary': '#24634b',
    '--sidebar-primary-foreground': '#fcfdfc',
    '--sidebar-accent': '#e8edea',
    '--sidebar-accent-foreground': '#26342d',
    '--sidebar-border': '#c5cec9',
    '--sidebar-ring': '#24634b',
    '--surface': '#f2f5f3',
    '--surface-muted': '#e9eeeb',
    '--surface-elevated': '#fcfdfc',
    '--brand-surface': '#306c53',
    '--brand-surface-foreground': '#f7fbf8',
    '--brand-surface-muted-foreground': '#dfede4',
    '--brand-surface-border': '#24553f',
    '--border-subtle': 'color-mix(in oklab, var(--border) 72%, transparent)',
    '--background': '#f5f7f5',
    '--foreground': '#26342d',
  },
  dark: {
    '--selection': '#d3e1d8',
    '--selection-foreground': '#1e2a23',
    '--selection-surface': '#3a4940',
    '--background': '#1c2420',
    '--foreground': '#edf3ef',
    '--card': '#252f29',
    '--card-foreground': '#f4f8f5',
    '--popover': '#252f29',
    '--popover-foreground': '#f4f8f5',
    '--primary': '#94cbb0',
    '--primary-foreground': '#15271d',
    '--secondary': '#35433b',
    '--secondary-foreground': '#eef5f0',
    '--muted': '#2d3932',
    '--muted-foreground': '#b8c7bd',
    '--accent': '#344e3e',
    '--accent-foreground': '#eef5f0',
    '--destructive': '#f2a8b7',
    '--destructive-foreground': '#321c22',
    '--border': '#53665a',
    '--input': '#809287',
    '--ring': '#94cbb0',
    '--chart-1': '#94cbb0',
    '--chart-2': '#9abda7',
    '--chart-3': '#d6a35a',
    '--chart-4': '#d58e67',
    '--chart-5': '#efb5c0',
    '--status-info': '#b8d8c5',
    '--status-info-surface': '#2e4939',
    '--status-warning': '#f0c27c',
    '--status-warning-surface': '#4e3c28',
    '--sidebar': '#18201c',
    '--sidebar-foreground': '#edf3ef',
    '--sidebar-primary': '#94cbb0',
    '--sidebar-primary-foreground': '#15271d',
    '--sidebar-accent': '#2f3d34',
    '--sidebar-accent-foreground': '#eef5f0',
    '--sidebar-border': '#4c6053',
    '--sidebar-ring': '#94cbb0',
    '--surface': '#202a24',
    '--surface-muted': '#2f3d34',
    '--surface-elevated': '#34433a',
    '--brand-surface': '#2c5140',
    '--brand-surface-foreground': '#f4f8f5',
    '--brand-surface-muted-foreground': '#d2e4d9',
    '--brand-surface-border': '#668c75',
    '--border-subtle': 'color-mix(in oklab, var(--border) 76%, transparent)',
  },
}
const original = {
  light: {
    '--card': '#fcf9f1',
    '--card-foreground': '#29332c',
    '--popover': '#fcf9f1',
    '--popover-foreground': '#29332c',
    '--selection': '#555247',
    '--selection-foreground': '#fffaf3',
    '--selection-surface': '#e7e0ce',
    '--primary': '#244c3b',
    '--primary-foreground': '#fcf9f1',
    '--secondary': '#e9e7db',
    '--secondary-foreground': '#29332c',
    '--muted': '#ede9df',
    '--muted-foreground': '#62665d',
    '--accent': '#e5e9de',
    '--accent-foreground': '#29332c',
    '--destructive': '#962f43',
    '--destructive-foreground': '#fff8f5',
    '--border': '#c9c3b5',
    '--input': '#918e7f',
    '--ring': '#244c3b',
    '--chart-1': '#244c3b',
    '--chart-2': '#607258',
    '--chart-3': '#a46f2c',
    '--chart-4': '#7b4f2f',
    '--chart-5': '#962f43',
    '--status-info': '#455d4e',
    '--status-info-surface': '#e0e8dd',
    '--status-warning': '#87571f',
    '--status-warning-surface': '#f1e2c8',
    '--radius': '0.5rem',
    '--control-height': '2.5rem',
    '--sidebar': '#f0ede3',
    '--sidebar-foreground': '#29332c',
    '--sidebar-primary': '#244c3b',
    '--sidebar-primary-foreground': '#fcf9f1',
    '--sidebar-accent': '#e9e7db',
    '--sidebar-accent-foreground': '#29332c',
    '--sidebar-border': '#c9c3b5',
    '--sidebar-ring': '#244c3b',
    '--surface': '#f3efe5',
    '--surface-muted': '#e8e5d9',
    '--surface-elevated': '#fcf9f1',
    '--brand-surface': '#355f4c',
    '--brand-surface-foreground': '#fffaf1',
    '--brand-surface-muted-foreground': '#d9e5dd',
    '--brand-surface-border': '#294b3b',
    '--border-subtle': 'color-mix(in oklab, var(--border) 72%, transparent)',
    '--background': '#f7f3e9',
    '--foreground': '#29332c',
  },
  dark: {
    '--selection': '#ded5bd',
    '--selection-foreground': '#24251f',
    '--selection-surface': '#403e34',
    '--background': '#20231f',
    '--foreground': '#f3eee4',
    '--card': '#2b2d27',
    '--card-foreground': '#f7f2e9',
    '--popover': '#2b2d27',
    '--popover-foreground': '#f7f2e9',
    '--primary': '#b6cbb9',
    '--primary-foreground': '#17251d',
    '--secondary': '#594a39',
    '--secondary-foreground': '#f5eee2',
    '--muted': '#32352e',
    '--muted-foreground': '#c2baa9',
    '--accent': '#425447',
    '--accent-foreground': '#f5f0e7',
    '--destructive': '#f2a8b7',
    '--destructive-foreground': '#321b18',
    '--border': '#665f52',
    '--input': '#817768',
    '--ring': '#b6cbb9',
    '--chart-1': '#b6cbb9',
    '--chart-2': '#9fb48e',
    '--chart-3': '#d6a35a',
    '--chart-4': '#d58e67',
    '--chart-5': '#efb5ad',
    '--status-info': '#b9cfbd',
    '--status-info-surface': '#35483a',
    '--status-warning': '#f0c27c',
    '--status-warning-surface': '#4e3c28',
    '--sidebar': '#1c1f1b',
    '--sidebar-foreground': '#f3eee4',
    '--sidebar-primary': '#b6cbb9',
    '--sidebar-primary-foreground': '#17251d',
    '--sidebar-accent': '#34382f',
    '--sidebar-accent-foreground': '#f5f0e7',
    '--sidebar-border': '#575247',
    '--sidebar-ring': '#b6cbb9',
    '--surface': '#252922',
    '--surface-muted': '#34382f',
    '--surface-elevated': '#373a32',
    '--brand-surface': '#324d3f',
    '--brand-surface-foreground': '#f7f2e9',
    '--brand-surface-muted-foreground': '#c9d8cd',
    '--brand-surface-border': '#5c7565',
    '--border-subtle': 'color-mix(in oklab, var(--border) 76%, transparent)',
  },
}

function direction(
  mode: PaletteMode,
  primary: string,
  canvas: string,
  paper: string,
  ink: string,
  mutedInk: string,
  selection: string,
  selectedSurface: string,
): PaletteTokens {
  return {
    ...current[mode],
    '--primary': primary,
    '--ring': primary,
    '--sidebar-primary': primary,
    '--sidebar-ring': primary,
    '--chart-1': primary,
    '--surface-muted': canvas,
    '--background': canvas,
    '--sidebar': canvas,
    '--card': paper,
    '--popover': paper,
    '--surface-elevated': paper,
    '--foreground': ink,
    '--card-foreground': ink,
    '--popover-foreground': ink,
    '--secondary-foreground': ink,
    '--accent-foreground': ink,
    '--sidebar-foreground': ink,
    '--muted-foreground': mutedInk,
    '--selection': selection,
    '--selection-surface': selectedSurface,
    '--secondary': selectedSurface,
    '--accent': selectedSurface,
    '--sidebar-accent': selectedSurface,
    '--surface': `color-mix(in srgb, ${paper} 70%, ${canvas})`,
    '--muted': `color-mix(in srgb, ${paper} 70%, ${canvas})`,
    '--border': mode === 'light' ? '#bec8c2' : '#586b60',
  }
}

export const workshopPalettes: Array<WorkshopPalette> = [
  {
    id: 'forest',
    name: 'Soft forest',
    description: 'Cool stone, white paper and natural forest green.',
    ...current,
  },
  {
    id: 'pine',
    name: 'Pine & paper',
    description:
      'The current app palette: warm stone and soft paper, with a rich pine accent.',
    light: direction(
      'light',
      '#285b43',
      '#eeece8',
      '#fcfbf8',
      '#30372f',
      '#62695f',
      '#55594c',
      '#e4e6dc',
    ),
    dark: direction(
      'dark',
      '#a9c7ab',
      '#272a24',
      '#20251f',
      '#f0f3ea',
      '#bfc9b9',
      '#d9decc',
      '#41493a',
    ),
  },
  {
    id: 'river',
    name: 'River green',
    description:
      'A cooler blue-green accent with pale mineral surfaces. Fresh and more contemporary.',
    light: direction(
      'light',
      '#24656a',
      '#e8eff0',
      '#fbfdfd',
      '#27373b',
      '#596a70',
      '#405b62',
      '#dce8eb',
    ),
    dark: direction(
      'dark',
      '#90c9cb',
      '#253339',
      '#1c292e',
      '#eaf4f5',
      '#b5cbd0',
      '#c5e0e5',
      '#354c54',
    ),
  },
  {
    id: 'ink',
    name: 'Ink & mint',
    description:
      'Crisp white, neutral grey and a near-black green. The strongest contrast and least background tint.',
    light: direction(
      'light',
      '#203f35',
      '#eef0ef',
      '#ffffff',
      '#252c29',
      '#5e6862',
      '#3e4c45',
      '#e1e9e4',
    ),
    dark: direction(
      'dark',
      '#9cd8b8',
      '#292e2b',
      '#1b211e',
      '#f0f5f2',
      '#bdc9c1',
      '#d3e4da',
      '#36473e',
    ),
  },
  {
    id: 'original',
    name: 'Original cream',
    description: 'The earlier yellow-toned palette, kept here as a reference.',
    ...original,
  },
]

export function paletteContrast(foreground: string, background: string) {
  if (!/^#[\da-f]{6}$/i.test(foreground) || !/^#[\da-f]{6}$/i.test(background))
    return undefined
  const luminance = (hex: string) =>
    [1, 3, 5]
      .map((offset) => parseInt(hex.slice(offset, offset + 2), 16) / 255)
      .map((c) => (c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4))
      .reduce((sum, c, i) => sum + c * [0.2126, 0.7152, 0.0722][i], 0)
  const values = [luminance(foreground), luminance(background)].sort(
    (a, b) => a - b,
  )
  return (values[1] + 0.05) / (values[0] + 0.05)
}
