export const horseBreeds = [
  'Akhal-Teke',
  'American Paint Horse',
  'American Quarter Horse',
  'Andalusian',
  'Appaloosa',
  'Arab cross',
  'Arabian',
  'Ardennes',
  'Australian Stock Horse',
  'Belgian Draft',
  'Black Forest Horse',
  'Breton',
  'Cleveland Bay',
  'Clydesdale',
  'Cob',
  'Connemara',
  'Criollo',
  'Crossbred',
  'Dartmoor Pony',
  'Dutch Warmblood',
  'Exmoor',
  'Fell Pony',
  'Fjord Horse',
  'Friesian',
  'Friesian cross',
  'Gypsy Cob',
  'Haflinger',
  'Hanoverian',
  'Highland',
  'Holsteiner',
  'Icelandic Horse',
  'Irish Cob',
  'Irish Draught',
  'Irish Sport Horse',
  'Kentucky Mountain Saddle Horse',
  'Lipizzaner',
  'Lusitano',
  'Miniature Horse',
  'Missouri Fox Trotter',
  'Morgan',
  'Mustang',
  'Native cross',
  'New Forest',
  'Oldenburg',
  'Orlov Trotter',
  'Paso Fino',
  'Percheron',
  'Polish Warmblood',
  'Pottok',
  'Rocky Mountain Horse',
  'Selle Français',
  'Shetland Pony',
  'Shire',
  'Sport Horse',
  'Standardbred',
  'Suffolk Punch',
  'Tennessee Walking Horse',
  'Thoroughbred',
  'Trakehner',
  'Warmblood',
  'Welsh Cob',
  'Welsh Pony',
  'Welsh Section A',
  'Welsh Section B',
  'Welsh Section C',
  'Welsh Section D',
  'Westphalian',
  'Zangersheide',
  'Other',
] as const

export type HorseBreed = (typeof horseBreeds)[number]
