// Regional additions: PZHK studbooks and RBST native equine listings.
// https://www.pzhk.pl/en/pzhk/about-us/
// https://www.rbst.org.uk/watchlist/equine/
export const horseBreeds = [
  'Akhal-Teke',
  'American Paint Horse',
  'American Quarter Horse',
  'Andalusian',
  'Appaloosa',
  'Arab cross',
  'Arabian',
  'Ardennes',
  'Australian Stock Horse',
  'Belgian Draft',
  'Black Forest Horse',
  'Breton',
  'Cleveland Bay',
  'Clydesdale',
  'Cob',
  'Connemara',
  'Criollo',
  'Crossbred',
  'Dales Pony',
  'Dartmoor Pony',
  'Dutch Warmblood',
  'Eriskay Pony',
  'Exmoor',
  'Fell Pony',
  'Fjord Horse',
  'Friesian',
  'Friesian cross',
  'Gypsy Cob',
  'Hackney Horse',
  'Hackney Pony',
  'Haflinger',
  'Hanoverian',
  'Highland',
  'Holsteiner',
  'Hucul Horse',
  'Icelandic Horse',
  'Irish Cob',
  'Irish Draught',
  'Irish Sport Horse',
  'Kentucky Mountain Saddle Horse',
  'Lipizzaner',
  'Lusitano',
  'Malopolska Horse',
  'Miniature Horse',
  'Missouri Fox Trotter',
  'Morgan',
  'Mustang',
  'Native cross',
  'New Forest',
  'Oldenburg',
  'Orlov Trotter',
  'Paso Fino',
  'Percheron',
  'Polish Ardennes',
  'Polish Coldblood',
  'Polish Konik',
  'Polish Pony',
  'Polish Sport Horse',
  'Polish Warmblood',
  'Pottok',
  'Rocky Mountain Horse',
  'Selle Français',
  'Shetland Pony',
  'Shire',
  'Silesian Horse',
  'Sport Horse',
  'Standardbred',
  'Suffolk Punch',
  'Tennessee Walking Horse',
  'Thoroughbred',
  'Trakehner',
  'Warmblood',
  'Welsh Cob',
  'Welsh Pony',
  'Welsh Section A',
  'Welsh Section B',
  'Welsh Section C',
  'Welsh Section D',
  'Westphalian',
  'Wielkopolska Horse',
  'Zangersheide',
  'Other',
] as const

export type HorseBreed = (typeof horseBreeds)[number]
