import { formatMediumDateKey } from '#/lib/dateDisplay'
import type { Locale } from 'shared/i18n/locale'
import { translateEventChange } from 'shared/i18n/eventChanges'
import { localeInstances } from '#/i18n/resources'
import type { StableAuditEntry } from './stableSettingsTypes'

export function formatAuditAction(action: string, locale: Locale = 'en') {
  const t = localeInstances[locale].t
  const labels: Record<string, string> = {
    'training.recorded': t('trainingViews.saved'),
    'stable.created': t('audit.stableCreated'),
    'stable.updated': t('audit.stableUpdated'),
    'stable.archived': t('audit.stableArchived'),
    'member_invitation.created': t('audit.memberInvited'),
    'member_invitation.resent': t('audit.invitationResent'),
    'member_invitation.revoked': t('audit.invitationRevoked'),
    'member_invitation.accepted': t('audit.invitationAccepted'),
    'member_invitation.declined': t('audit.invitationDeclined'),
    'member_invitation.activated': t('audit.accessActivated'),
    'member_invitation.accepted_pending_plan': t('audit.invitationPendingPlan'),
    'member.removed': t('audit.memberRemoved'),
    'event.created': t('audit.eventCreated'),
    'event.updated': t('audit.eventUpdated'),
    'event_horse.approved': t('audit.horseApproved'),
    'event_horse.declined': t('audit.horseDeclined'),
    'event_horse.withdrawn': t('audit.horseWithdrawn'),
  }
  return labels[action] ?? t('audit.changed')
}

export function formatAuditActor(
  actor: StableAuditEntry['actor'],
  locale: Locale = 'en',
) {
  if (!actor) return localeInstances[locale].t('audit.formerUser')
  return (
    actor.preferredName ||
    [actor.firstName, actor.lastName].filter(Boolean).join(' ')
  )
}

export function formatStableAuditSummary(
  entry: Pick<StableAuditEntry, 'action' | 'summary' | 'details'>,
  locale: Locale = 'en',
) {
  const t = localeInstances[locale].t
  if (entry.details?.kind === 'training_recorded')
    return t('trainingViews.audit', {
      horse: entry.details.horseName,
      status: t(`training.status.${entry.details.status}`),
      date: formatMediumDateKey(entry.details.date, locale),
    })
  if (entry.details?.kind === 'event_changes') {
    return entry.details.changes
      .map((change) => translateEventChange(change, locale))
      .join(', ')
  }
  if (entry.details?.kind === 'member_removed') {
    return (
      [
        entry.details.memberName,
        entry.details.reassignedHorseCount > 0
          ? t('stables.reassigned', {
              count: entry.details.reassignedHorseCount,
            })
          : undefined,
      ]
        .filter(Boolean)
        .join(' · ') || undefined
    )
  }
  // These two legacy member summaries were generated by the server, never user input.
  if (entry.action === 'member.removed' && entry.summary) {
    const count = /^Removed member and reassigned (\d+) horses?$/.exec(
      entry.summary,
    )?.[1]
    if (count) return t('stables.reassigned', { count: Number(count) })
    const id = /^Removed member (\S+)$/.exec(entry.summary)?.[1]
    if (id) return t('audit.legacyMemberRemoved', { id })
  }
  // Old event summaries mixed system prose and user titles without a discriminator.
  // Preserve ambiguous legacy text instead of translating a person's event title.
  return entry.summary
}
