/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StablesLayoutRouteImport } from './routes/stables/_layout'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as StablesLayoutIndexRouteImport } from './routes/stables/_layout/index'
import { Route as StablesLayoutCreateRouteImport } from './routes/stables/_layout/create'
import { Route as StablesLayoutStableIdRouteImport } from './routes/stables/_layout/$stableId'
import { Route as StablesLayoutStableIdIndexRouteImport } from './routes/stables/_layout/$stableId/index'
import { Route as StablesLayoutStableIdHorsesRouteImport } from './routes/stables/_layout/$stableId/horses'
import { Route as StablesLayoutStableIdEventsRouteImport } from './routes/stables/_layout/$stableId/events'
import { Route as StablesLayoutStableIdEditRouteImport } from './routes/stables/_layout/$stableId/edit'
import { Route as StablesLayoutStableIdHorsesIndexRouteImport } from './routes/stables/_layout/$stableId/horses/index'
import { Route as StablesLayoutStableIdEventsIndexRouteImport } from './routes/stables/_layout/$stableId/events/index'
import { Route as StablesLayoutStableIdHorsesCreateRouteImport } from './routes/stables/_layout/$stableId/horses/create'
import { Route as StablesLayoutStableIdHorsesHorseIdRouteImport } from './routes/stables/_layout/$stableId/horses/$horseId'
import { Route as StablesLayoutStableIdEventsCreateRouteImport } from './routes/stables/_layout/$stableId/events/create'
import { Route as StablesLayoutStableIdEventsEventIdRouteImport } from './routes/stables/_layout/$stableId/events/$eventId'
import { Route as StablesLayoutStableIdHorsesHorseIdEditRouteImport } from './routes/stables/_layout/$stableId/horses/$horseId/edit'
import { Route as StablesLayoutStableIdEventsEventIdEditRouteImport } from './routes/stables/_layout/$stableId/events/$eventId/edit'

const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StablesLayoutRoute = StablesLayoutRouteImport.update({
  id: '/stables/_layout',
  path: '/stables',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const StablesLayoutIndexRoute = StablesLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StablesLayoutRoute,
} as any)
const StablesLayoutCreateRoute = StablesLayoutCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => StablesLayoutRoute,
} as any)
const StablesLayoutStableIdRoute = StablesLayoutStableIdRouteImport.update({
  id: '/$stableId',
  path: '/$stableId',
  getParentRoute: () => StablesLayoutRoute,
} as any)
const StablesLayoutStableIdIndexRoute =
  StablesLayoutStableIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StablesLayoutStableIdRoute,
  } as any)
const StablesLayoutStableIdHorsesRoute =
  StablesLayoutStableIdHorsesRouteImport.update({
    id: '/horses',
    path: '/horses',
    getParentRoute: () => StablesLayoutStableIdRoute,
  } as any)
const StablesLayoutStableIdEventsRoute =
  StablesLayoutStableIdEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => StablesLayoutStableIdRoute,
  } as any)
const StablesLayoutStableIdEditRoute =
  StablesLayoutStableIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => StablesLayoutStableIdRoute,
  } as any)
const StablesLayoutStableIdHorsesIndexRoute =
  StablesLayoutStableIdHorsesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StablesLayoutStableIdHorsesRoute,
  } as any)
const StablesLayoutStableIdEventsIndexRoute =
  StablesLayoutStableIdEventsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StablesLayoutStableIdEventsRoute,
  } as any)
const StablesLayoutStableIdHorsesCreateRoute =
  StablesLayoutStableIdHorsesCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => StablesLayoutStableIdHorsesRoute,
  } as any)
const StablesLayoutStableIdHorsesHorseIdRoute =
  StablesLayoutStableIdHorsesHorseIdRouteImport.update({
    id: '/$horseId',
    path: '/$horseId',
    getParentRoute: () => StablesLayoutStableIdHorsesRoute,
  } as any)
const StablesLayoutStableIdEventsCreateRoute =
  StablesLayoutStableIdEventsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => StablesLayoutStableIdEventsRoute,
  } as any)
const StablesLayoutStableIdEventsEventIdRoute =
  StablesLayoutStableIdEventsEventIdRouteImport.update({
    id: '/$eventId',
    path: '/$eventId',
    getParentRoute: () => StablesLayoutStableIdEventsRoute,
  } as any)
const StablesLayoutStableIdHorsesHorseIdEditRoute =
  StablesLayoutStableIdHorsesHorseIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => StablesLayoutStableIdHorsesHorseIdRoute,
  } as any)
const StablesLayoutStableIdEventsEventIdEditRoute =
  StablesLayoutStableIdEventsEventIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => StablesLayoutStableIdEventsEventIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/stables': typeof StablesLayoutRouteWithChildren
  '/stables/$stableId': typeof StablesLayoutStableIdRouteWithChildren
  '/stables/create': typeof StablesLayoutCreateRoute
  '/stables/': typeof StablesLayoutIndexRoute
  '/stables/$stableId/edit': typeof StablesLayoutStableIdEditRoute
  '/stables/$stableId/events': typeof StablesLayoutStableIdEventsRouteWithChildren
  '/stables/$stableId/horses': typeof StablesLayoutStableIdHorsesRouteWithChildren
  '/stables/$stableId/': typeof StablesLayoutStableIdIndexRoute
  '/stables/$stableId/events/$eventId': typeof StablesLayoutStableIdEventsEventIdRouteWithChildren
  '/stables/$stableId/events/create': typeof StablesLayoutStableIdEventsCreateRoute
  '/stables/$stableId/horses/$horseId': typeof StablesLayoutStableIdHorsesHorseIdRouteWithChildren
  '/stables/$stableId/horses/create': typeof StablesLayoutStableIdHorsesCreateRoute
  '/stables/$stableId/events/': typeof StablesLayoutStableIdEventsIndexRoute
  '/stables/$stableId/horses/': typeof StablesLayoutStableIdHorsesIndexRoute
  '/stables/$stableId/events/$eventId/edit': typeof StablesLayoutStableIdEventsEventIdEditRoute
  '/stables/$stableId/horses/$horseId/edit': typeof StablesLayoutStableIdHorsesHorseIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/stables/create': typeof StablesLayoutCreateRoute
  '/stables': typeof StablesLayoutIndexRoute
  '/stables/$stableId/edit': typeof StablesLayoutStableIdEditRoute
  '/stables/$stableId': typeof StablesLayoutStableIdIndexRoute
  '/stables/$stableId/events/$eventId': typeof StablesLayoutStableIdEventsEventIdRouteWithChildren
  '/stables/$stableId/events/create': typeof StablesLayoutStableIdEventsCreateRoute
  '/stables/$stableId/horses/$horseId': typeof StablesLayoutStableIdHorsesHorseIdRouteWithChildren
  '/stables/$stableId/horses/create': typeof StablesLayoutStableIdHorsesCreateRoute
  '/stables/$stableId/events': typeof StablesLayoutStableIdEventsIndexRoute
  '/stables/$stableId/horses': typeof StablesLayoutStableIdHorsesIndexRoute
  '/stables/$stableId/events/$eventId/edit': typeof StablesLayoutStableIdEventsEventIdEditRoute
  '/stables/$stableId/horses/$horseId/edit': typeof StablesLayoutStableIdHorsesHorseIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/stables/_layout': typeof StablesLayoutRouteWithChildren
  '/stables/_layout/$stableId': typeof StablesLayoutStableIdRouteWithChildren
  '/stables/_layout/create': typeof StablesLayoutCreateRoute
  '/stables/_layout/': typeof StablesLayoutIndexRoute
  '/stables/_layout/$stableId/edit': typeof StablesLayoutStableIdEditRoute
  '/stables/_layout/$stableId/events': typeof StablesLayoutStableIdEventsRouteWithChildren
  '/stables/_layout/$stableId/horses': typeof StablesLayoutStableIdHorsesRouteWithChildren
  '/stables/_layout/$stableId/': typeof StablesLayoutStableIdIndexRoute
  '/stables/_layout/$stableId/events/$eventId': typeof StablesLayoutStableIdEventsEventIdRouteWithChildren
  '/stables/_layout/$stableId/events/create': typeof StablesLayoutStableIdEventsCreateRoute
  '/stables/_layout/$stableId/horses/$horseId': typeof StablesLayoutStableIdHorsesHorseIdRouteWithChildren
  '/stables/_layout/$stableId/horses/create': typeof StablesLayoutStableIdHorsesCreateRoute
  '/stables/_layout/$stableId/events/': typeof StablesLayoutStableIdEventsIndexRoute
  '/stables/_layout/$stableId/horses/': typeof StablesLayoutStableIdHorsesIndexRoute
  '/stables/_layout/$stableId/events/$eventId/edit': typeof StablesLayoutStableIdEventsEventIdEditRoute
  '/stables/_layout/$stableId/horses/$horseId/edit': typeof StablesLayoutStableIdHorsesHorseIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/rss.xml'
    | '/sign-in/$'
    | '/stables'
    | '/stables/$stableId'
    | '/stables/create'
    | '/stables/'
    | '/stables/$stableId/edit'
    | '/stables/$stableId/events'
    | '/stables/$stableId/horses'
    | '/stables/$stableId/'
    | '/stables/$stableId/events/$eventId'
    | '/stables/$stableId/events/create'
    | '/stables/$stableId/horses/$horseId'
    | '/stables/$stableId/horses/create'
    | '/stables/$stableId/events/'
    | '/stables/$stableId/horses/'
    | '/stables/$stableId/events/$eventId/edit'
    | '/stables/$stableId/horses/$horseId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/rss.xml'
    | '/sign-in/$'
    | '/stables/create'
    | '/stables'
    | '/stables/$stableId/edit'
    | '/stables/$stableId'
    | '/stables/$stableId/events/$eventId'
    | '/stables/$stableId/events/create'
    | '/stables/$stableId/horses/$horseId'
    | '/stables/$stableId/horses/create'
    | '/stables/$stableId/events'
    | '/stables/$stableId/horses'
    | '/stables/$stableId/events/$eventId/edit'
    | '/stables/$stableId/horses/$horseId/edit'
  id:
    | '__root__'
    | '/'
    | '/rss.xml'
    | '/sign-in/$'
    | '/stables/_layout'
    | '/stables/_layout/$stableId'
    | '/stables/_layout/create'
    | '/stables/_layout/'
    | '/stables/_layout/$stableId/edit'
    | '/stables/_layout/$stableId/events'
    | '/stables/_layout/$stableId/horses'
    | '/stables/_layout/$stableId/'
    | '/stables/_layout/$stableId/events/$eventId'
    | '/stables/_layout/$stableId/events/create'
    | '/stables/_layout/$stableId/horses/$horseId'
    | '/stables/_layout/$stableId/horses/create'
    | '/stables/_layout/$stableId/events/'
    | '/stables/_layout/$stableId/horses/'
    | '/stables/_layout/$stableId/events/$eventId/edit'
    | '/stables/_layout/$stableId/horses/$horseId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SignInSplatRoute: typeof SignInSplatRoute
  StablesLayoutRoute: typeof StablesLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stables/_layout': {
      id: '/stables/_layout'
      path: '/stables'
      fullPath: '/stables'
      preLoaderRoute: typeof StablesLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stables/_layout/': {
      id: '/stables/_layout/'
      path: '/'
      fullPath: '/stables/'
      preLoaderRoute: typeof StablesLayoutIndexRouteImport
      parentRoute: typeof StablesLayoutRoute
    }
    '/stables/_layout/create': {
      id: '/stables/_layout/create'
      path: '/create'
      fullPath: '/stables/create'
      preLoaderRoute: typeof StablesLayoutCreateRouteImport
      parentRoute: typeof StablesLayoutRoute
    }
    '/stables/_layout/$stableId': {
      id: '/stables/_layout/$stableId'
      path: '/$stableId'
      fullPath: '/stables/$stableId'
      preLoaderRoute: typeof StablesLayoutStableIdRouteImport
      parentRoute: typeof StablesLayoutRoute
    }
    '/stables/_layout/$stableId/': {
      id: '/stables/_layout/$stableId/'
      path: '/'
      fullPath: '/stables/$stableId/'
      preLoaderRoute: typeof StablesLayoutStableIdIndexRouteImport
      parentRoute: typeof StablesLayoutStableIdRoute
    }
    '/stables/_layout/$stableId/horses': {
      id: '/stables/_layout/$stableId/horses'
      path: '/horses'
      fullPath: '/stables/$stableId/horses'
      preLoaderRoute: typeof StablesLayoutStableIdHorsesRouteImport
      parentRoute: typeof StablesLayoutStableIdRoute
    }
    '/stables/_layout/$stableId/events': {
      id: '/stables/_layout/$stableId/events'
      path: '/events'
      fullPath: '/stables/$stableId/events'
      preLoaderRoute: typeof StablesLayoutStableIdEventsRouteImport
      parentRoute: typeof StablesLayoutStableIdRoute
    }
    '/stables/_layout/$stableId/edit': {
      id: '/stables/_layout/$stableId/edit'
      path: '/edit'
      fullPath: '/stables/$stableId/edit'
      preLoaderRoute: typeof StablesLayoutStableIdEditRouteImport
      parentRoute: typeof StablesLayoutStableIdRoute
    }
    '/stables/_layout/$stableId/horses/': {
      id: '/stables/_layout/$stableId/horses/'
      path: '/'
      fullPath: '/stables/$stableId/horses/'
      preLoaderRoute: typeof StablesLayoutStableIdHorsesIndexRouteImport
      parentRoute: typeof StablesLayoutStableIdHorsesRoute
    }
    '/stables/_layout/$stableId/events/': {
      id: '/stables/_layout/$stableId/events/'
      path: '/'
      fullPath: '/stables/$stableId/events/'
      preLoaderRoute: typeof StablesLayoutStableIdEventsIndexRouteImport
      parentRoute: typeof StablesLayoutStableIdEventsRoute
    }
    '/stables/_layout/$stableId/horses/create': {
      id: '/stables/_layout/$stableId/horses/create'
      path: '/create'
      fullPath: '/stables/$stableId/horses/create'
      preLoaderRoute: typeof StablesLayoutStableIdHorsesCreateRouteImport
      parentRoute: typeof StablesLayoutStableIdHorsesRoute
    }
    '/stables/_layout/$stableId/horses/$horseId': {
      id: '/stables/_layout/$stableId/horses/$horseId'
      path: '/$horseId'
      fullPath: '/stables/$stableId/horses/$horseId'
      preLoaderRoute: typeof StablesLayoutStableIdHorsesHorseIdRouteImport
      parentRoute: typeof StablesLayoutStableIdHorsesRoute
    }
    '/stables/_layout/$stableId/events/create': {
      id: '/stables/_layout/$stableId/events/create'
      path: '/create'
      fullPath: '/stables/$stableId/events/create'
      preLoaderRoute: typeof StablesLayoutStableIdEventsCreateRouteImport
      parentRoute: typeof StablesLayoutStableIdEventsRoute
    }
    '/stables/_layout/$stableId/events/$eventId': {
      id: '/stables/_layout/$stableId/events/$eventId'
      path: '/$eventId'
      fullPath: '/stables/$stableId/events/$eventId'
      preLoaderRoute: typeof StablesLayoutStableIdEventsEventIdRouteImport
      parentRoute: typeof StablesLayoutStableIdEventsRoute
    }
    '/stables/_layout/$stableId/horses/$horseId/edit': {
      id: '/stables/_layout/$stableId/horses/$horseId/edit'
      path: '/edit'
      fullPath: '/stables/$stableId/horses/$horseId/edit'
      preLoaderRoute: typeof StablesLayoutStableIdHorsesHorseIdEditRouteImport
      parentRoute: typeof StablesLayoutStableIdHorsesHorseIdRoute
    }
    '/stables/_layout/$stableId/events/$eventId/edit': {
      id: '/stables/_layout/$stableId/events/$eventId/edit'
      path: '/edit'
      fullPath: '/stables/$stableId/events/$eventId/edit'
      preLoaderRoute: typeof StablesLayoutStableIdEventsEventIdEditRouteImport
      parentRoute: typeof StablesLayoutStableIdEventsEventIdRoute
    }
  }
}

interface StablesLayoutStableIdEventsEventIdRouteChildren {
  StablesLayoutStableIdEventsEventIdEditRoute: typeof StablesLayoutStableIdEventsEventIdEditRoute
}

const StablesLayoutStableIdEventsEventIdRouteChildren: StablesLayoutStableIdEventsEventIdRouteChildren =
  {
    StablesLayoutStableIdEventsEventIdEditRoute:
      StablesLayoutStableIdEventsEventIdEditRoute,
  }

const StablesLayoutStableIdEventsEventIdRouteWithChildren =
  StablesLayoutStableIdEventsEventIdRoute._addFileChildren(
    StablesLayoutStableIdEventsEventIdRouteChildren,
  )

interface StablesLayoutStableIdEventsRouteChildren {
  StablesLayoutStableIdEventsEventIdRoute: typeof StablesLayoutStableIdEventsEventIdRouteWithChildren
  StablesLayoutStableIdEventsCreateRoute: typeof StablesLayoutStableIdEventsCreateRoute
  StablesLayoutStableIdEventsIndexRoute: typeof StablesLayoutStableIdEventsIndexRoute
}

const StablesLayoutStableIdEventsRouteChildren: StablesLayoutStableIdEventsRouteChildren =
  {
    StablesLayoutStableIdEventsEventIdRoute:
      StablesLayoutStableIdEventsEventIdRouteWithChildren,
    StablesLayoutStableIdEventsCreateRoute:
      StablesLayoutStableIdEventsCreateRoute,
    StablesLayoutStableIdEventsIndexRoute:
      StablesLayoutStableIdEventsIndexRoute,
  }

const StablesLayoutStableIdEventsRouteWithChildren =
  StablesLayoutStableIdEventsRoute._addFileChildren(
    StablesLayoutStableIdEventsRouteChildren,
  )

interface StablesLayoutStableIdHorsesHorseIdRouteChildren {
  StablesLayoutStableIdHorsesHorseIdEditRoute: typeof StablesLayoutStableIdHorsesHorseIdEditRoute
}

const StablesLayoutStableIdHorsesHorseIdRouteChildren: StablesLayoutStableIdHorsesHorseIdRouteChildren =
  {
    StablesLayoutStableIdHorsesHorseIdEditRoute:
      StablesLayoutStableIdHorsesHorseIdEditRoute,
  }

const StablesLayoutStableIdHorsesHorseIdRouteWithChildren =
  StablesLayoutStableIdHorsesHorseIdRoute._addFileChildren(
    StablesLayoutStableIdHorsesHorseIdRouteChildren,
  )

interface StablesLayoutStableIdHorsesRouteChildren {
  StablesLayoutStableIdHorsesHorseIdRoute: typeof StablesLayoutStableIdHorsesHorseIdRouteWithChildren
  StablesLayoutStableIdHorsesCreateRoute: typeof StablesLayoutStableIdHorsesCreateRoute
  StablesLayoutStableIdHorsesIndexRoute: typeof StablesLayoutStableIdHorsesIndexRoute
}

const StablesLayoutStableIdHorsesRouteChildren: StablesLayoutStableIdHorsesRouteChildren =
  {
    StablesLayoutStableIdHorsesHorseIdRoute:
      StablesLayoutStableIdHorsesHorseIdRouteWithChildren,
    StablesLayoutStableIdHorsesCreateRoute:
      StablesLayoutStableIdHorsesCreateRoute,
    StablesLayoutStableIdHorsesIndexRoute:
      StablesLayoutStableIdHorsesIndexRoute,
  }

const StablesLayoutStableIdHorsesRouteWithChildren =
  StablesLayoutStableIdHorsesRoute._addFileChildren(
    StablesLayoutStableIdHorsesRouteChildren,
  )

interface StablesLayoutStableIdRouteChildren {
  StablesLayoutStableIdEditRoute: typeof StablesLayoutStableIdEditRoute
  StablesLayoutStableIdEventsRoute: typeof StablesLayoutStableIdEventsRouteWithChildren
  StablesLayoutStableIdHorsesRoute: typeof StablesLayoutStableIdHorsesRouteWithChildren
  StablesLayoutStableIdIndexRoute: typeof StablesLayoutStableIdIndexRoute
}

const StablesLayoutStableIdRouteChildren: StablesLayoutStableIdRouteChildren = {
  StablesLayoutStableIdEditRoute: StablesLayoutStableIdEditRoute,
  StablesLayoutStableIdEventsRoute:
    StablesLayoutStableIdEventsRouteWithChildren,
  StablesLayoutStableIdHorsesRoute:
    StablesLayoutStableIdHorsesRouteWithChildren,
  StablesLayoutStableIdIndexRoute: StablesLayoutStableIdIndexRoute,
}

const StablesLayoutStableIdRouteWithChildren =
  StablesLayoutStableIdRoute._addFileChildren(
    StablesLayoutStableIdRouteChildren,
  )

interface StablesLayoutRouteChildren {
  StablesLayoutStableIdRoute: typeof StablesLayoutStableIdRouteWithChildren
  StablesLayoutCreateRoute: typeof StablesLayoutCreateRoute
  StablesLayoutIndexRoute: typeof StablesLayoutIndexRoute
}

const StablesLayoutRouteChildren: StablesLayoutRouteChildren = {
  StablesLayoutStableIdRoute: StablesLayoutStableIdRouteWithChildren,
  StablesLayoutCreateRoute: StablesLayoutCreateRoute,
  StablesLayoutIndexRoute: StablesLayoutIndexRoute,
}

const StablesLayoutRouteWithChildren = StablesLayoutRoute._addFileChildren(
  StablesLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SignInSplatRoute: SignInSplatRoute,
  StablesLayoutRoute: StablesLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
